---
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rafael
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: testpassword123
    ports:
      - 5432:5432
