name: Api Workflow

on:
    pull_request:
        branches: main

jobs:
    api-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 21.x

            - name: Install packages
              run: npm install

            - name: Run builder
              run: CI=false && npm run build-test

            - name: Run tests
              run: npm run test
